# Generated by Django 5.2.6 on 2025-11-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0016_saledetails_frkwt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('firmname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
