# Generated by Django 5.2.6 on 2025-11-18 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0017_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemaster',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.firm'),
        ),
    ]
