# Generated by Django 5.2.6 on 2025-11-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0018_salemaster_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamaentry',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brokerapp.firm'),
        ),
        migrations.AddField(
            model_name='jamaentry',
            name='firm_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='naameentry',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brokerapp.firm'),
        ),
        migrations.AddField(
            model_name='naameentry',
            name='firm_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
