# Generated by Django 5.2.6 on 2025-11-18 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0019_jamaentry_firm_jamaentry_firm_name_naameentry_firm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemaster',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.firm'),
        ),
    ]
