# Generated by Django 5.2.6 on 2025-11-19 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0020_purchasemaster_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamaentry',
            name='party_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='naameentry',
            name='party_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jamaentry',
            name='firm_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jamaentry',
            name='party',
            field=models.ForeignKey(blank=True, db_column='partyname', null=True, on_delete=django.db.models.deletion.PROTECT, to='brokerapp.headparty'),
        ),
        migrations.AlterField(
            model_name='jamaentry',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='naameentry',
            name='firm_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='naameentry',
            name='party',
            field=models.ForeignKey(blank=True, db_column='partyname', null=True, on_delete=django.db.models.deletion.PROTECT, to='brokerapp.headparty'),
        ),
        migrations.AlterField(
            model_name='naameentry',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
