# Generated by Django 5.2.6 on 2025-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0021_jamaentry_party_name_naameentry_party_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='frkwt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='FrkWt'),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='tbwt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='TBWt'),
        ),
    ]
