# Generated by Django 5.2.6 on 2026-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0022_purchasedetails_frkwt_purchasedetails_tbwt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemaster',
            name='batav_sign',
            field=models.CharField(choices=[('PLUS', '+'), ('MINUS', '-')], default='PLUS', max_length=5),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='dr_sign',
            field=models.CharField(choices=[('PLUS', '+'), ('MINUS', '-')], default='PLUS', max_length=5),
        ),
    ]
