# Generated by Django 5.2.6 on 2026-02-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0023_purchasemaster_batav_sign_purchasemaster_dr_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemaster',
            name='batav_sign',
            field=models.CharField(choices=[('PLUS', '+'), ('MINUS', '-')], default='PLUS', max_length=5),
        ),
        migrations.AddField(
            model_name='salemaster',
            name='dr_sign',
            field=models.CharField(choices=[('PLUS', '+'), ('MINUS', '-')], default='PLUS', max_length=5),
        ),
    ]
