# Generated by Django 5.2.6 on 2026-02-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0024_salemaster_batav_sign_salemaster_dr_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasemaster',
            name='batav_sign',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='dr_sign',
        ),
        migrations.RemoveField(
            model_name='salemaster',
            name='batav_sign',
        ),
        migrations.RemoveField(
            model_name='salemaster',
            name='dr_sign',
        ),
    ]
