# Generated by Django 5.2.6 on 2026-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0025_remove_purchasemaster_batav_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemaster',
            name='advance_sign',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='other_sign',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='salemaster',
            name='advance_sign',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='salemaster',
            name='other_sign',
            field=models.CharField(default='-', max_length=1),
        ),
    ]
